# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayImg_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 949)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(1020, 50, 100, 25))
        self.btn_open.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_open.setObjectName("btn_open")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(1020, 140, 100, 25))
        self.btn_play.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_play.setObjectName("btn_play")
        self.label_ImgSize = QtWidgets.QLabel(self.centralwidget)
        self.label_ImgSize.setGeometry(QtCore.QRect(1020, 420, 161, 16))
        self.label_ImgSize.setObjectName("label_ImgSize")
        self.label_fps = QtWidgets.QLabel(self.centralwidget)
        self.label_fps.setGeometry(QtCore.QRect(1020, 240, 72, 15))
        self.label_fps.setObjectName("label_fps")
        self.lineEdit_fps = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fps.setGeometry(QtCore.QRect(1020, 270, 151, 31))
        self.lineEdit_fps.setObjectName("lineEdit_fps")
        self.qid = QtWidgets.QLabel(self.centralwidget)
        self.qid.setGeometry(QtCore.QRect(1100, 540, 71, 20))
        self.qid.setObjectName("qid")
        self.label_CurrentImg = QtWidgets.QLabel(self.centralwidget)
        self.label_CurrentImg.setGeometry(QtCore.QRect(1020, 540, 71, 20))
        self.label_CurrentImg.setObjectName("label_CurrentImg")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(20, 30, 981, 811))
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.label_CurrentImgName = QtWidgets.QLabel(self.centralwidget)
        self.label_CurrentImgName.setGeometry(QtCore.QRect(20, 860, 111, 20))
        self.label_CurrentImgName.setObjectName("label_CurrentImgName")
        self.label_ImgName = QtWidgets.QLabel(self.centralwidget)
        self.label_ImgName.setGeometry(QtCore.QRect(150, 860, 411, 21))
        self.label_ImgName.setObjectName("label_ImgName")
        self.label_jump = QtWidgets.QLabel(self.centralwidget)
        self.label_jump.setGeometry(QtCore.QRect(1020, 680, 72, 15))
        self.label_jump.setObjectName("label_jump")
        self.lineEdit_jump = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jump.setGeometry(QtCore.QRect(1100, 670, 71, 31))
        self.lineEdit_jump.setObjectName("lineEdit_jump")
        self.btn_jump = QtWidgets.QPushButton(self.centralwidget)
        self.btn_jump.setGeometry(QtCore.QRect(1070, 710, 100, 25))
        self.btn_jump.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_jump.setObjectName("btn_jump")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(570, 860, 72, 15))
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(650, 850, 351, 31))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.btn_ApplyFPS = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ApplyFPS.setGeometry(QtCore.QRect(1070, 310, 93, 25))
        self.btn_ApplyFPS.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_ApplyFPS.setObjectName("btn_ApplyFPS")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open.setText(_translate("MainWindow", "导入图片"))
        self.btn_play.setText(_translate("MainWindow", "播放"))
        self.label_ImgSize.setText(_translate("MainWindow", "图片尺寸适应窗口大小"))
        self.label_fps.setText(_translate("MainWindow", "帧率："))
        self.lineEdit_fps.setText(_translate("MainWindow", "10"))
        self.qid.setText(_translate("MainWindow", "x"))
        self.label_CurrentImg.setText(_translate("MainWindow", "当前图片："))
        self.label_CurrentImgName.setText(_translate("MainWindow", "当前图片名称："))
        self.label_ImgName.setText(_translate("MainWindow", "ImgName"))
        self.label_jump.setText(_translate("MainWindow", "图片跳转："))
        self.btn_jump.setText(_translate("MainWindow", "跳转"))
        self.label_path.setText(_translate("MainWindow", "图片路径："))
        self.lineEdit_path.setText(_translate("MainWindow", "./photo"))
        self.btn_ApplyFPS.setText(_translate("MainWindow", "Apply FPS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
